### ISSUE TITLE
Getting error after protectin console example with vmp 3.5.0

### ISSUE THREAD

**Issue by fknMega** [Biitez/Authenty-ME#3]
I get this **error** for some reason after I protect the **console example** using **vmprotect 3.5.0**
`
Unhandled Exception: System.Net.WebException: This application could not be found
   at 192577C5.1163257C(Exception 03BA7126)
   at 192577C5.5D222CE9(Object[] 04576B9A, Int32 79BC5045)
   at Authenty_ME_Example.Program.Main(String[] args)
`

**Without protecting** I get no error and everything works **perfec**t.

**Comment by biitez** [comment]
Hello, try to use the new sample console and Library https://github.com/biitez/AuthentyLib
